name: FriCAS CI on x64 Linux (with Julia support - SBCL based)

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      JULIA_VERSION: '1.11.2'
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install sbcl libgmp-dev libxpm-dev cl-hunchentoot python3 python3-sphinx
    - name: Download and install Julia
      run: |
        wget https://julialang-s3.julialang.org/bin/linux/x64/1.11/julia-${JULIA_VERSION}-linux-x86_64.tar.gz
        tar zxf julia-${JULIA_VERSION}-linux-x86_64.tar.gz
        sudo cp -rf julia-${JULIA_VERSION}/* /usr/local/
        sudo ldconfig
    - name: install Julia libraries
      run: |
        julia -e "import Pkg;Pkg.add(\"Nemo\");Pkg.add(\"Suppressor\");Pkg.add(\"SpecialFunctions\")"
    - name: configure
      run: ./configure --with-gmp --enable-julia --enable-hunchentoot || cat config.log
    - name: make
      run: |
        make -j4 --output-sync
    - name: make html doc
      run: 
        make -j4 --output-sync htmldoc
    - name: make check
      run: make -j4 check
    - name: Create artifact archives
      run: |
        rm -r target/*/src
        tar -cjf FriCAS-linux-x86_64-${{ github.sha }}.tar.bz2 target/
    - name: Upload Linux binary
      uses: actions/upload-artifact@v4
      with:
        name: FriCAS-linux-x86_64-binary
        path: FriCAS-linux-x86_64-${{ github.sha }}.tar.bz2
