name: FriCAS CI on Windows

on: [push, pull_request]
permissions: {}

jobs:
  build:

    runs-on: windows-2022
    timeout-minutes: 30
    env:
      SBCL_VER: 2.3.2
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        install: make mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-gmp gmp-devel zip
    - name: download and install SBCL
      run: |
        wget https://downloads.sourceforge.net/project/sbcl/sbcl/${SBCL_VER}/sbcl-${SBCL_VER}-x86-64-windows-binary.msi
        msiexec -i sbcl-${SBCL_VER}-x86-64-windows-binary.msi -passive

    - uses: actions/checkout@v4
    - name: configure and make
      run: |
        export SBCL_HOME="/c/Program Files/Steel Bank Common Lisp/"
        export PATH="$SBCL_HOME":$PATH
        mkdir ../build && cd ../build
        ../jlfricas/configure --with-lisp=sbcl --enable-gmp || cat config.log
        make -j4 --output-sync

    - name: Create artifact archives
      run: |
        cp -rp ../build/target/x86_64-w64-mingw32 FriCAS-windows-x86_64
        rm FriCAS-windows-x86_64/bin/fricas
        cp /ucrt64/bin/libgmp-10.dll FriCAS-windows-x86_64/lib/
        zip -r FriCAS-windows-x86_64-${{ github.sha }}.zip FriCAS-windows-x86_64

    - name: Upload Windows binary
      uses: actions/upload-artifact@v4
      with:
        name: FriCAS-windows-x86_64-binary
        path: FriCAS-windows-x86_64-${{ github.sha }}.zip

    - name: make check
      run: cd ../build && make check -j4 --output-sync
